# Site settings
title: Wahyu Rahmaniar 
#twitter_username: wahyurahmaniar
name: Wahyu Rahmaniar

# Build settings
#markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://technologination.blogspot.com/
 - title: GitHub
   url: https://github.com/wahyurahmaniar  
 - title: LinkedIn
   url: https://www.linkedin.com/in/wahyu-rahmaniar-22041987/
 - title: Facebook
   url: https://www.facebook.com/wahyu.rahmaniar
 - title: Twitter
   url: https://twitter.com/WahyuRahmaniar

#Any buzzword skills you want to include
skills:
 - C/C++
 - C#
 - MATLAB
 - Visual Basic
 - Python
 - Tensorflow
 - Pytorch
 - Java
 
skills2:
 - Arduino
 - AVR Studio
 - Bascom AVR
 - Protel PCB
 - Eagle PCB
 - Solidworks
 - Verilog
 - PLC
 - Raspberry Pi
 - NVIDIA Jetson

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
#roles:
# - title: CTO
#   start: 2017
#   end: Ongoing
#   employer: Basement Crowd
#   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2009
   #departement: Electronics and Instrumentation
   subject: Robotics and Control
   school: Universitas Gadjah Mada
 - level: Master of Science (M.Sc.)
   date: 2014
   #departement: Electrical Engineering
   subject: Robotics and Computer Vision
   school: National Central University
 - level: Doctor of Philosophy (P.hD.)
   date: 2020
   #departement: Electrical Engineering
   subject: Computer Vision and Artificial Intelligence
   school: National Central University

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   talks:
    - title: Artificial Intelligence in Real-Life
      host: Sekolah Tinggi Teknologi Bandung
      date: July, 2021
   talks2:
    - title: When Remote Sensing Meets Artificial Intelligence 
      host: Universitas Negeri Makasar
      date: December, 2021

#List of interesting Github repo/projects to include - optional
#github:
# - wahyurahmaniar/wahyurahmaniar.github.io

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  Currently I'm a Postdoctoral Researcher at National Taipei University of Technology, Taiwan. I received the B.S. degree in Electronics and Instrumentation from Universitas Gadjah Mada, Yogyakarta, Indonesia, in 2009 and Ph.D. degree in Electrical Engineering from National Central University, Taiwan, in 2020. 
  My research interests are in the areas of robotics, computer vision, image processing, and artificial intelligence (AI). <br/><br/>
  
  The research I conducted in the field of computer vision and image processing, including AI, I used C ++ or Python programming on Windows or Linux operating systems. Overall, I have at least 10 years experience in programming. And for the AI field, I have studied it since I took a Ph.D. degree until now for about 7 years.
  For intelligent systems, I focus more on developing algorithms or frameworks that can run systems in the real-time in the actual environment. Besides, I also understand well enough the theory and mathematics for these systems, including machine learning and deep learning. One of my interests in AI research is that I want to create my own network or method. 
  I have also been a reviewer in several journals and a guest speaker at several seminars. <br/><br/>


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <p><strong>Year</strong>: November 2021 - now <br/>
   <strong>Company</strong>: National Taipei University of Technology <br/>
   <strong>Position</strong>: Postdoctoral Researcher <br/>
   <strong>Subject</strong>: Programming, commputer vision, image processing, artificial intelligence <br/>
   </p>
   <br/>
   <p><strong>Year</strong>: December 2018 - October 2021 <br/>
   <strong>Company</strong>: Issa Technology <br/>
   <strong>Position</strong>: Software Engineer <br/>
   <strong>Subject</strong>: Programming, commputer vision, image processing, artificial intelligence <br/>
   </p>
   <br/>
   <p><strong>Year</strong>: October 2017 – January 2018 <br/>
   <strong>Company</strong>: Shibaura Institute of Technology <br/>
   <strong>Position</strong>: Exchange Student <br/>
   <strong>Subject</strong>: Automatic localization of UAV in an unknown environment <br/>
   </p>
   <br/>
   <p><strong>Year</strong>: June 2017 - August 2017 <br/>
   <strong>Company</strong>: Ubiik Inc <br/>
   <strong>Position</strong>: Software Engineer <br/>
   <strong>Subject</strong>: Program and embedded system for Smart Power Meter <br/>
   </p>
   <br/>
   <p><strong>Year</strong>: May 2009 - August 2013 <br/>
   <strong>Position</strong>: Freelancer <br/>
   <strong>Subject</strong>: Programming and electronics<br/>
   </p>
   <br/>
   <p><strong>Year</strong>: November 2010 - October 2011 <br/>
   <strong>Company</strong>: Institut Teknologi Sepuluh Nopember <br/>
   <strong>Position</strong>: Research Assistant <br/>
   <strong>Subject</strong>: Programming and electronics <br/>
   </p>
   <br/>
   <p><strong>Year</strong>: May 2010 – October 2010 <br/>
   <strong>Company</strong>: Universitas Indonesia <br/>
   <strong>Position</strong>: Research Assistant <br/>
   <strong>Subject</strong>: Programming and electronics <br/>
   </p>
   <br/>
   <p><strong>Year</strong>: August 2009 - January 2010 <br/>
   <strong>Company</strong>: Universitas Gadjah Mada <br/>
   <strong>Position</strong>: Laboratory Assistant <br/>
   <strong>Subject</strong>: Teaching class and experiment in electronics and programming <br/>
   </p>
